feat: Configuration on account page
PoCInnovation/InterPlanetaryCloud pull request #124
Opened 2023-03-02 21:18 UTC by EdenComp

# Description

This PR adds a second card under the Account card, the Configuration page.
It replaces the old component ConfigPage

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [X] I have assigned this PR to myself
- [X] I have added at least 1 reviewer
- [X] I have added the needed labels
- [X] I have linked this PR to an issue
- [X] I have linked this PR to a milestone
- [X] I have linked this PR to a project
- [ ] I have tested this code
- [ ] I have added / updated tests (unit / functionals / end-to-end / ...)
- [ ] I have updated the README and other relevant documents (guides...)
- [ ] I have added sufficient documentation both in code, as well as in the READMEs

# Additional comments

There is currently some problems with the theme: will investigate

2023-03-02 22:15 UTC, RezaRahemtola requested changes
The global design is here but the values are missing.

Don't forget to handle responsive and keep future configuration options in mind :+1:

2023-03-02 22:15 UTC, RezaRahemtola commented on src/components/ConfigPage.tsx
> +			</HStack>
Try to split this in multiple components, it's pretty huge right now :smile:

2023-03-17 10:11 UTC, RezaRahemtola requested changes
When testing locally I can't edit the configuration options (except for the light/dark theme), which was possible before.

2023-03-18 17:22 UTC, RezaRahemtola approved these changes

2023-03-18 23:07 UTC, lucas-louis approved these changes
LGTM

2023-03-19 20:40 UTC, RezaRahemtola approved these changes

2023-03-19 20:42 UTC, merged