fix: CONTRIBUTING with project name
PoCInnovation/InterPlanetaryCloud pull request #53
Opened 2022-04-19 20:15 UTC by RezaRahemtola

# Description

CONTRIBUTING.md template updated with the project name and repository link
Related to issue #41

# Changes include

- [x] Bugfix (non-breaking change that solves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have added the needed labels
- [x] I have linked this PR to an issue
- [x] I have linked this PR to a milestone
- [x] I have linked this PR to a project
- [x] I have updated the README and other relevant documents (guides...)
- [x] I have added sufficient documentation both in code, as well as in the READMEs

2022-04-20 00:03 UTC, adrienfort requested changes
LGTM but this PR doesn't respect our workflow : remind that you have first to make a PR from `fix/contributing` to `dev`, and then once it's merged, from `dev` to `master`.

It's important to strictly follow this workflow, especially at the beginning of the project and even for small changes.

Moreover, please do not remove check points in the PR's checklist. You've removed these two :
```
 - [ ] I have tested this code
 - [ ] I have added / updated tests (unit / functionals / end-to-end / ...)
```
Be aware that it's ok if everything is not ticked, sometimes you don't need it. But don't remove them.

Otherwise, you've assigned this PR to the right issue with an assignee, that's great !

2022-04-20 00:12 UTC, adrienfort commented
> LGTM but this PR doesn't respect our workflow : remind that you have first to make a PR from `fix/contributing` to `dev`, and then once it's merged, from `dev` to `master`.
> 
> It's important to strictly follow this workflow, especially at the beginning of the project and even for small changes.
> 
> Moreover, please do not remove check points in the PR's checklist. You've removed these two :
> 
> ```
>  - [ ] I have tested this code
>  - [ ] I have added / updated tests (unit / functionals / end-to-end / ...)
> ```
> 
> Be aware that it's ok if everything is not ticked, sometimes you don't need it. But don't remove them.
> 
> Otherwise, you've assigned this PR to the right issue with an assignee, that's great !

You can change the branch `master`

2022-04-20 07:47 UTC, RezaRahemtola commented
@adrienfort I used your PR #40 that added this template as an example for this one, and as it was merged directly on master (the `dev` branch currently has an old version of CONTRIBUTING.md ) I thought it was ok to merge it on master.

Same for the checkpoints, you also removed these two in your PR so I did the same.

Anyway it's fixed now !

2022-04-20 09:05 UTC, TomChv reviewed
Can you correctly rebase your PR? I see a bunch of commits from dependabot and merge commit.

git rebase dev (or main) should be enough.
Otherwise, LGTM.

2022-04-20 09:07 UTC, adrienfort commented
> ay it's fixed now !

Yes your are right ! I forgot this

2022-04-20 09:21 UTC, RezaRahemtola commented
> git rebase dev (or main) should be enough. Otherwise, LGTM.

I tried `git rebase origin/master` while on the `dev` branch but I don't have write access to publish the changes:

> git push origin dev:dev
> remote: error: GH006: Protected branch update failed for refs/heads/dev.        
> remote: error: At least 1 approving review is required by reviewers with write access.        
> To github.com:PoCInnovation/InterPlanetaryCloud.git
>  ! [remote rejected] dev -> dev (protected branch hook declined)
> error: failed to push some refs to 'github.com:PoCInnovation/InterPlanetaryCloud.git'

2022-04-20 09:30 UTC, adrienfort commented
> > git rebase dev (or main) should be enough. Otherwise, LGTM.
> 
> I tried `git rebase origin/master` while on the `dev` branch but I don't have write access to publish the changes:
> 
> > git push origin dev:dev
> > remote: error: GH006: Protected branch update failed for refs/heads/dev.
> > remote: error: At least 1 approving review is required by reviewers with write access.
> > To github.com:PoCInnovation/InterPlanetaryCloud.git
> > ! [remote rejected] dev -> dev (protected branch hook declined)
> > error: failed to push some refs to 'github.com:PoCInnovation/InterPlanetaryCloud.git'

Yes ! That's because the `dev` branch has protection rules

2022-04-20 10:14 UTC, RezaRahemtola commented
> Can you correctly rebase your PR? I see a bunch of commits from dependabot and merge commit.

Fixed !

2022-04-20 10:23 UTC, adrienfort commented
Before merging, @RezaRahemtola @TristanMasselot @Samoten777 have you played on your own with PoC's project template ?
As mention in issue #47

2022-04-21 13:46 UTC, Samoten777 commented
Yes, I used it in a personal repository, and it works perfectly fine ! 👍🏾

2022-04-26 16:04 UTC, merged